# pyproject.toml
[tool.pytest.ini_options]
log_file = "/Library/Application Support/Perceptive Automation/Indigo 2022.2/Logs/net.segment7.powerview/plugin.log"
log_file_format = "%(asctime)s %(levelname)s %(message)s"
log_file_level = "DEBUG"
log_level = "DEBUG"
minversion = "6.0"
testpaths = [
    "pv_tests",
]
