# pyproject.toml
[tool.pytest.ini_options]
# log_file = "/Library/Application Support/Perceptive Automation/Indigo 2022.2/Logs/net.segment7.powerview/pytestLog.log"
log_file_format = "%(asctime)s.%(msecs).0f\t%(levelname)s\t%(funcName)s\t\t%(message)s"
log_file_date_format = "%y-%m-%d %H:%M:%S"
log_auto_indent = "True"
log_file_level = "DEBUG"
log_level = "DEBUG"
#junit_logging = "out-err"
junit_logging = "all"
junit_suite_name = "PowerView Tests"
minversion = "6.0"
testpaths = [
    "pv_tests",
]
